config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "dashboard#index"

  post 'fortune', to: 'dashboard#fortune'

  resources :randoms, only: [:index, :update, :destroy] do
    collection do
      post :prepend
      post :append
    end
    member do
      post :replace
      post :add_before
      post :add_after
    end
  end

  resources :interviews, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @fortune = %w(大吉 中吉 小吉 凶).sample
  end

  def fortune
    @fortune = %w(大吉 中吉 小吉 凶).sample
    render partial: 'fortune'
  end
end

app/controllers/interviews_controller.rb
class InterviewsController < ApplicationController
  def index
  end
end

app/controllers/randoms_controller.rb
class RandomsController < ApplicationController
  def index
  end

  def prepend
    @random = rand(1000)
    @dom_id = generate_dom_id

    respond_to do |format|
      format.turbo_stream { render partial: 'prepend' }
      format.html         { redirect_to randoms_url }
    end
  end

  def append
    @random = rand(1000)
    @dom_id = generate_dom_id

    respond_to do |format|
      format.turbo_stream { render partial: 'append' }
      format.html         { redirect_to randoms_url }
    end
  end

  def replace
    @random = rand(1000)
    @target_dom_id = params[:id]
    @dom_id = generate_dom_id

    respond_to do |format|
      format.turbo_stream { render partial: 'replace' }
      format.html         { redirect_to randoms_url }
    end
  end

  def update
    @random = rand(1000)
    @dom_id = params[:id]

    respond_to do |format|
      format.turbo_stream { render partial: 'update' }
      format.html         { redirect_to randoms_url }
    end
  end

  def destroy
    # 実際のところこの処理だけならブラウザだけで完結できるが
    # デモとして実装
    # 実際のアプリではデータ削除をやったあとに削除用のHTML片を返す感じ
    @dom_id = params[:id]

    respond_to do |format|
      format.turbo_stream { render partial: 'destroy' }
      format.html         { redirect_to randoms_url }
    end
  end

  def add_before
    @random = rand(1000)
    @target_dom_id = params[:id]
    @dom_id = generate_dom_id

    respond_to do |format|
      format.turbo_stream { render partial: 'add_before' }
      format.html         { redirect_to randoms_url }
    end
  end

  def add_after
    @random = rand(1000)
    @target_dom_id = params[:id]
    @dom_id = generate_dom_id

    respond_to do |format|
      format.turbo_stream { render partial: 'add_after' }
      format.html         { redirect_to randoms_url }
    end
  end

  private

  def generate_dom_id
    "random_#{ (Time.current.to_f * 1000).to_i }" # かぶらなければ何でも
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/randoms_helper.rb
module RandomsHelper
end

app/views/dashboard/_fortune.html.erb
<%= turbo_frame_tag 'fortune' do %>
  <p>今日の運勢は<%= @fortune %>です</p>

  <%= form_with url: fortune_path do |f| %>
    <%= f.submit '引き直す！' %>
  <% end %>
<% end %>

app/views/dashboard/index.html.erb
<p>こんにちは</p>

<%#= render partial: 'fortune' %>
<%= turbo_frame_tag 'fortune' do %>
  <%= form_with url: fortune_path do |f| %>
    <%= f.submit 'おみくじを引く！' %>
  <% end %>
<% end %>

app/views/interviews/index.html.erb
<%= form_with url: false, id: 'interview', data: { controller: 'form' } do |form| %>
  <p data-controller="validation" data-form-target="validation" data-validation-length-value="10" data-validation-validity-value="false" data-validation-form-id-value="interview">
    <%= form.label :field1, '項目1（10文字まで）' %>
    <%= form.text_field :field1, 'data-validation-target': 'field', 'data-action': 'input->validation#validate' %>
    <span data-validation-target="errorMessage"></span>
  </p>
  <p data-controller="validation" data-form-target="validation" data-validation-length-value="15" data-validation-validity-value="false" data-validation-form-id-value="interview">
    <%= form.label :field2, '項目2（15文字まで）' %>
    <%= form.text_field :field2, 'data-validation-target': 'field', 'data-action': 'input->validation#validate' %>
    <span data-validation-target="errorMessage"></span>
  </p>
  <%= form.button 'data-form-target': 'submit', disabled: true %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelloHotwire</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/randoms/_add_after.turbo_stream.erb
<%= turbo_stream.after @target_dom_id do %>
  <%= render partial: 'random' %>
<% end %>

app/views/randoms/_add_before.turbo_stream.erb
<%= turbo_stream.before @target_dom_id do %>
  <%= render partial: 'random' %>
<% end %>

app/views/randoms/_append.turbo_stream.erb
<%= turbo_stream.append "randoms" do %>
  <%= render partial: 'random' %>
<% end %>

app/views/randoms/_destroy.turbo_stream.erb
<%= turbo_stream.remove @dom_id %>

app/views/randoms/_prepend.turbo_stream.erb
<%= turbo_stream.prepend "randoms" do %>
  <p><%= @random %></p>
<% end %>

app/views/randoms/_random.turbo_stream.erb
<div>
<p><%= @random %></p>

  <%#= button_to '削除する', random_path(id: @dom_id), method: :delete %>
</div>

app/views/randoms/_replace.turbo_stream.erb
<%= turbo_stream.replace @target_dom_id do %>
  <%= render partial: 'random' %>
<% end %>

app/views/randoms/_update.turbo_stream.erb
<%= turbo_stream.update @dom_id do %>
  <p><%= @random %></p>

  <%= form_with url: replace_random_path(id: @dom_id) do |f| %>
    <%= f.submit '振り直す1' %>
  <% end %>

  <%= form_with url: random_path(id: @dom_id), method: :patch do |f| %>
    <%= f.submit '振り直す2' %>
  <% end %>

  <%= button_to '削除する', random_path(id: @dom_id), method: :delete %>

  <%= form_with url: add_before_random_path(id: @dom_id) do |f| %>
    <%= f.submit '上に追加' %>
  <% end %>

  <%= form_with url: add_after_random_path(id: @dom_id) do |f| %>
    <%= f.submit '下に追加' %>
  <% end %>
<% end %>

app/views/randoms/index.html.erb
<div id="randoms">
</div>

<%= form_with url: append_randoms_path do |f| %>
  <%= f.submit '末尾に追加' %>
<% end %>